name: develop_branch_wf

on:
  push:
    branches:
      - develop

jobs:
    job1:
        name: job 1
        runs-on: ubuntu-latest
        steps:
        - name: step one
          uses: actions/checkout@v2
        - name: step two 
          run: uptime
    jobs2: 
        name: job 2
        runs-on: ubuntu-latest
        steps:
        - name: step one
          uses: actions/checkout@v2
        - name: step two
          run: whoami
